apiVersion: v1
kind: Service
metadata:
  name: rajat-python-app-service
  annotations:
    endpointslice.kubernetes.io/skip: "true"
spec:
  type: NodePort
  selector:
    app: my-python-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30007  # NodePort to expose the service on localhost
